server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001
  requestLog:
    type: classic
    timeZone: IST
    appenders:
      - type: file
        currentLogFilename: product/requests.log
        archive: true
        archivedLogFilenamePattern: product/requests.log.%d{yyyy-MM-dd}
        archivedFileCount: 50

logging:
  level: INFO
  appenders:
    - type: console
    - type: file
      threshold: INFO
      timeZone: IST
      logFormat: "%date %level [%thread] %logger{0} [%X{id}] %msg%n"
      currentLogFilename: product/product.log
      archive: true
      archivedLogFilenamePattern: product/product.log.%d{yyyy-MM-dd}
      archivedFileCount: 20

database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password:
  url: jdbc:mysql://${DB_HOST:-localhost}/product?autoReconnect=true&useSSL=false
  properties:
   charSet: UTF-8
   hibernate.show_sql: false
   hibernate.hbm2ddl.auto: validate
   hibernate.session.events.log: false
   hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s
  # the SQL query to executeAction when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"
  # the minimum resourceId of connections to keep open
  minSize: 8

  # the maximum resourceId of connections to keep open
  maxSize: 128
  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false
  checkConnectionOnBorrow: true
  maxConnectionAge : 10s

swagger:
  resourcePackage: com.product.demo.resource